Create github actions configuration (closes #2)
allegro/bigcache-bench pull request #5
Opened 2019-10-25 23:12 UTC by ottojo

This creates a github actions workflow with build and test jobs
Closes #2

2019-10-26 07:16 UTC, cristaloleg requested changes

2019-10-26 07:16 UTC, cristaloleg commented on .github/workflows/go.yml
> +    steps:
Please, add a version matrix

2019-12-10 15:17 UTC, janisz approved these changes

2019-12-10 15:22 UTC, cristaloleg approved these changes

2019-12-10 15:23 UTC, merged